{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"your_username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":109,"line":"338","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":109,"line":"338","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"your_username\"\n    at Client._connectionCallback (C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-03-12 13:28:15"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"your_username\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":109,"line":"338","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":109,"line":"338","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"your_username\"\n    at Client._connectionCallback (C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\sequelize\\lib\\dialects\\postgres\\connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:518:28)\n    at C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\pg-protocol\\dist\\parser.js:36:17)\n    at Socket.<anonymous> (C:\\Users\\User\\Desktop\\calorie-tracker\\Backend\\node_modules\\pg-protocol\\dist\\index.js:11:42)\n    at Socket.emit (node:events:518:28)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)","timestamp":"2025-03-12 13:35:54"}
